# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish-internal"
baseURL = "https://caydock.com/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disableLanguages = []
disablePathToLower = false

# Global TDK settings
title = "CayDock"
description = "CayDock is my personal project showcase website, recording the challenges, experiences, and growth I encountered in independent development and overseas ventures"
keywords = ["CayDock", "independent development", "overseas", "independent developer", "independent developer overseas", "independent developer diary", "independent developer blog"]

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = "G-XXXXXXXXX"

[pagination]
  pagerSize = 12

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10

# URL重写规则 - 恢复原来的 posts/ 格式
[permalinks]
  posts = "/posts/:slug/"

# Cloudflare Pages 优化配置
[build]
  writeStats = true

# 压缩和优化
[minify]
  disableXML = false
  minifyOutput = true

# 缓存控制（CF Pages 会自动处理）
[caches]
  [caches.getjson]
    dir = ":cacheDir"
    maxAge = -1
  [caches.getcsv]
    dir = ":cacheDir"
    maxAge = -1
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = -1
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = -1
  [caches.modules]
    dir = ":cacheDir/modules"
    maxAge = -1
