disabled = false
languageCode = "zh-CN"
languageName = "中文"
weight = 2
title = "CayDock"


[params]
  displayName = "中文"
  isoCode = "zh-CN"
  rtl = false
  dateFormat = "2006年1月2日"
  description = "CayDock 是我的个人产品导航网站，记录了我在独立开发过程中遇到的挑战、经验和成长，希望能为其他独立开发者提供一些启发和帮助"
  keywords = ["CayDock", "独立开发", "独立开发者", "独立开发者日记", "独立开发者博客", "出海开发"]
  pageTitle = "CayDock - 我的独立开发者出海日记"
  mainSections = ["posts"]
  twitter = "@caydock"  # Twitter handle for twitter:site meta tag
  
  [params.article]
    sharingLinks = [ "twitter", "facebook", "linkedin", "email", "whatsapp", "telegram", "line"]
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Cayden"
  email = "cay.dev@hotmail.com"
  image = "images/cay.webp"
  imageQuality = 96
  bio = "专注独立开发出海，记录独立开发出海路上的点点滴滴"
  links = [
    { email = "mailto:cay.dev@hotmail.com" },
    { github = "https://github.com/caydock" },
    { twitter = "https://twitter.com/caydock" },
    { wechat = "https://mp.weixin.qq.com/s/gvdeyiK3GyOIeFqB1IWsFA" },
  ]
