disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "CayDock"


[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "CayDock is my personal project showcase website, recording the challenges, experiences, and growth I encountered in independent development and overseas ventures. Hope to provide some inspiration and help for other independent developers"
  keywords = ["CayDock", "independent development", "overseas", "independent developer", "independent developer overseas", "independent developer diary", "independent developer blog"]
  pageTitle = "CayDock - Dock Ideas, Launch Products"
  twitter = "@caydock"  # Twitter handle for twitter:site meta tag
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Cayden"
  email = "cay.dev@hotmail.com"
  image = "images/cay.webp"
  imageQuality = 96
  bio = "Independent developer sharing daily experiences, challenges and growth in the journey of building products"
  links = [
    { email = "mailto:cay.dev@hotmail.com" },
    { github = "https://github.com/caydock" },
    { twitter = "https://twitter.com/caydock" },
  ]
