name: Hexo Deploy CI
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Blog Source
        uses: actions/checkout@v2
        with:
          ref: develop
          submodules: 'true'
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: Setup Hexo CLI
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_TOKEN }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "w3cay@hotmail.com"
          git config --global user.name "w3cay"
          npm install hexo-cli -g
          npm install
      - name: Hexo deploy
        run: |
          hexo clean
          hexo generate
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: vhost276.cloudvhost.cn
          username: webmaster@HA675619
          password: ${{ secrets.FTP_PSW }}
          local-dir: ./public/
          server-dir: ./WEB/
